spring:
  application:
    name: loan-mate
  config:
    import:
      - classpath:application-db.yml
      - classpath:application-auth.yml
      - classpath:env.properties
  profiles:
    active: ${PROFILE}

server:
  port: ${PORT:8080}
  servlet:
    session:
      cookie:
        name: LOANMATESESSION
