server:
  port: 8081
spring:
  application:
    name: loan-mate
  config:
    import:
      - classpath:application-db.yml
      - classpath:application-auth.yml
      - classpath:application-cdc.yml
      - classpath:env.properties
  profiles:
    active: ${PROFILE}

# 테스트용 유저 토큰
corebanking:
  token: ${COREBANKING_TOKEN}
