
cdc:
  enabled: ${CDC_ENABLED}
  kafka:
    bootstrap-servers: ${CDC_KAFKA_BOOTSTRAP_SERVERS}
    topic: ${CDC_KAFKA_TOPIC}
    consumer-group-id: ${CDC_KAFKA_CONSUMER_GROUP}
    consumer-auto-start: ${CDC_KAFKA_CONSUMER_AUTO_START}