spring:
  application:
    name: loan-mate
  config:
    import:
      - classpath:application-db.yml
      - classpath:application-auth.yml
  profiles:
    active: ${PROFILE}

  jpa:
    hibernate:
      ddl-auto: ${DATABASE_DDL_AUTO}
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: ${PORT:8080}
  servlet:
    session:
      cookie:
        name: LOANMATESESSION
