server:
  port: 8081
spring:
  application:
    name: bank
  config:
    import:
      - classpath:application-db.yml
      - classpath:application-cdc.yml
  profiles:
    active: ${PROFILE}

# 테스트용 유저 토큰
corebanking:
  token: ${COREBANKING_TOKEN}
