spring:
  application:
    name: loan-mate
  config:
    import:
      - classpath:application-db.yml
      - classpath:application-auth.yml
      - classpath:application-cdc.yml
  profiles:
    active: ${PROFILE}

server:
  port: ${PORT:8080}
  servlet:
    session:
      cookie:
        name: LOANMATESESSION
  forward-headers-strategy: framework

app:
  front-success-url: ${FRONT_URL}/login/success
  front-fail-url: ${FRONT_URL}/login/fail
  
ai-server:
  api-url: ${AI_SERVER_API_URL}