server:
  port: 8081
spring:
  application:
    name: bank
  config:
    import:
      - classpath:application-db.yml
      - classpath:env.properties
  profiles:
    active: ${PROFILE}

  jpa:
    hibernate:
      ddl-auto: ${DATABASE_DDL_AUTO}
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# 테스트용 유저 토큰
corebanking:
  token: ${COREBANKING_TOKEN}