server:
  port: 8081
spring:
  application:
    name: bank
  config:
    import:
      - classpath:application-db.yml
  profiles:
    active: ${PROFILE}

  jpa:
    hibernate:
      ddl-auto: ${DATABASE_DDL_AUTO}
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect